name: Deploy to Lightsail

on:
  push:
    branches:
      - main   # pipeline runs automatically on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

      - name: Deploy on Lightsail
        env:
          HOST: ${{ secrets.LIGHTSAIL_HOST }}
          USER: ${{ secrets.LIGHTSAIL_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no ${USER}@${HOST} << 'EOF'
            set -e
            cd /home/ubuntu/dermacare-backend   # 👈 your actual project path

            # Stop old containers
            docker compose down

            # Pull latest code
            git fetch origin main
            git reset --hard origin/main

            # Start containers (fresh restart)
            docker compose up -d --remove-orphans
          EOF
